# Generated by Django 5.0.2 on 2025-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_alter_game_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
